eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5        # 心跳时间
    lease-expiration-duration-in-seconds: 15    # 过期时间


enable:
  needLogin: false

hot:
  topic:
    total: 10   # 显示热搜数量
    refreshTime: 30    #总热度榜刷新时间

batch:
  size: 500   #批量处理点赞收藏的大小

task:
  browserTimes: 1
  upTotal: 10


#lcn的服务端地址
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070


