spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 197877346hmr
      url: jdbc:mysql://39.105.0.169:33306/irh?characterEncoding=UTF-8&amp;useUnicode=true&amp;allowMultiQueries=true
      initial-size: 5     # 初始化大小
      max-active: 20      # 连接池中最大的活动数
      max-wait: 30000                             # 最大连接等待时间
      time-between-eviction-runs-millis: 60000    # 配置检测可以关闭的空闲连接间隔时间
      validation-query: select '1' from dual      # 测试连接
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5        # 心跳时间
    lease-expiration-duration-in-seconds: 15    # 过期时间

debug:
  true

enable:
  needLogin: false

hot:
  topic:
    total: 10   # 显示热搜数量
    refreshTime: 30    #总热度榜刷新时间

batch:
  size: 500   #批量处理点赞收藏的大小

task:
  browserTimes: 1
  upTotal: 10
