server:
  port: 10700

spring:
  application:
    name: user-service
  profiles:
    active: dev

mybatis:
  mapper-locations: mapper/*
  type-aliases-package: top.imuster.user.api.pojo  #别名扫描

feign:
  hystrix:
    enabled: true
hot:
  topic:
    total: 0   # 显示热搜数量
    refreshTime: 0    #总热度榜刷新时间

aliyun:                   #阿里云实名认证配置
  realNameAuth:
    host: http://dm-51.data.aliyun.com
    path: /rest/160601/ocr/ocr_idcard.json
    appCode: 00840a9616a643ee8d98e323d938ef5f  #500次调用

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /customer/login
      - /customer/register
      - /error
      - /user/feign/login/
      - /user/feign/roleAndAuth




