server:
  port: 10000

spring:
  application:
    name: security-service
  profiles:
    active: dev

mybatis:
  mapper-locations: mapper/*
  type-aliases-package: top.imuster.security.api.pojo

auth:
  tokenValiditySeconds: 1200  #token存储到redis的过期时间
  clientId: irhWebApp
  clientSecret: irhWebApp
  cookieDomain: www.imuster.top
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/irh.keystore
    secret: irhkeystore
    alias: irhkey
    password: imuster

token:
  expireTime: 86400 #token过期时间

hot:
  topic:
    total: 0   # 显示热搜数量
    refreshTime: 0    #总热度榜刷新时间

management:
  security:
    enabled: false

baidu:    # 调用百度AI的accessToken
  accessToken: 24.54d8034729e43e77dd2c3b0d7e947236.2592000.1591933911.282335-19129665    # access token
  templateSign: 7cf8f229fe578025234e3556515daf63    # 识别一卡通的模板id
  bdRecogniseUrl: https://aip.baidubce.com/rest/2.0/solution/v1/iocr/recognise

aliyun:
  realNameAuth:
    host: http://dm-51.data.aliyun.com
    path: /rest/160601/ocr/ocr_idcard.json
    appCode: 00840a9616a643ee8d98e323d938ef5f

ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 50000  #请求连接的超时时间
  ReadTimeout: 60000 #请求处理的超时时间


wxApp:
  appId: wxc7911b0a367c62b6
  appSecret: 937cb3f2017441121d3393c627555301
  UrlPrefix: https://api.weixin.qq.com/sns/jscode2session?

file:
  urlPrefix: http://39.105.0.169:8080/


secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /customer/login
      - /customer/register
      - /error
      - /user/feign/login/
      - /user/feign/roleAndAuth