server:
  port: 10010
spring:
  application:
    name: irh-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5           # 设置拉取服务的间隔时间
zuul:
  prefix: /api      # 配置前缀
  routes:
    user-service: /user/**    # 路由到用户微服务
    goods-service: /goods/**    # 路由到商品的微服务
    order-service: /**   #路由到订单微服务



