server:
  port: 10900
  ssl:
    key-store-password: AOzksRxv
    key-store: classpath:imuster.pfx
    key-store-type: PKCS12
spring:
  profiles:
    active: dev
  application:
    name: irh-gateway
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  prefix: /api      # 配置前缀
  routes:
    user-service: user/**    # 路由到用户微服务
    goods-service: goods/**    # 路由到商品的微服务
    order-service: order/**   #路由到订单微服务
    security-service: security/**  #路由到认证中心微服务
    forum-service: life/**    #路由到生活微服务
    file-service: file/**    #路由到文件微服务
    message-service: message/**   #路由到搜索和消息中心
  sensitive-headers:          # zuul网关会屏蔽掉请求头中的一些敏感信息，设置成空可以覆盖默认配置，即不屏蔽任何消息
  add-proxy-headers: true

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 240000 #断路器超时时间，默认1000ms

irh:
  security:
    publicKey: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgaVB+OnTTnhG8/plZ2dihsA6KXnL3BuDTByPlIbCw6dz7aB2PU+/YsdQKig8HWQFq/cNpUkWBU0+d2VQwTQp/9uqdp9nK3VMSzzHkcZkFTpOK51tzFqmvP6CH2FWkVh/bJo+vfkm32XFY9L6C+NYKGJdC7FpcBIs3132d+lbRbOp4j/6keq8BaqNWwbOU+2I/UeAGA7GlHp1FSe/0e4OT/t62jwqVLXQhkTSYhcoSaal+zAr3kVveQnLXqhAeQe1n0WnhSodQpLeKrU49mqt0ciz6oXxTsZglsh/RbCv76/5tpAAxSu+N92G7P+pvlxuLo+wku6Q7IsFhR0IIS12KwIDAQAB-----END PUBLIC KEY-----

ribbon:
  ReadTimeout: 960000
  ConnectTimeout: 960000