server:
  port: 20200


mybatis:
  mapper-locations: mapper/*
  type-aliases-package: top.imuster.life.api.pojo

spring:
  profiles:
    active: dev
  application:
    name: forum-service

feign:     # 启动hystrix
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://39.105.0.169:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5        # 心跳时间
    lease-expiration-duration-in-seconds: 15    # 过期时间


